DROP SCHEMA IF EXISTS PRIMERA_CHAMBA;
CREATE SCHEMA PRIMERA_CHAMBA;
#ESTO ES UN COMENTARIO 
USE PRIMERA_CHAMBA;

CREATE TABLE PRIMERITA_CHAMBA (
	NOMBRE VARCHAR(20) PRIMARY KEY,
    EDAD INT 
    
    );