DROP SCHEMA IF EXISTS CARRRERITA;

CREATE SCHEMA CARRRERITA;

USE CARRRERITA;

CREATE TABLE PARTICIPANTE (
    ID INT PRIMARY KEY,
    DNI VARCHAR(10) NOT NULL UNIQUE,
    NOMBRE VARCHAR(100) NOT NULL,
    EDAD INT CHECK (EDAD > 18)
);

CREATE TABLE ORGANIZADOR (
    ID INT PRIMARY KEY,
    EDAD INT CHECK (EDAD > 18),
    CARGO VARCHAR(100),
    FECHA_INICIO DATE
);

CREATE TABLE BICICLETA (
    ID INT PRIMARY KEY,
    MODELO VARCHAR(100),
    ES_ELECTRICA BOOLEAN,
    PESO_GRAMOS INT DEFAULT 100
);

CREATE TABLE DIRECTOR (
    ID_ORGANIZADOR INT PRIMARY KEY,
    ANIOS_EXPERIENCIA INT CHECK (ANIOS_EXPERIENCIA >= 5)
);


CREATE TABLE CARRERA (
    ID INT PRIMARY KEY,
    FECHA DATE,
    LUGAR_INICIO VARCHAR(100),
    LUGAR_FIN VARCHAR(100),
    ID_DIRECTOR INT,
    FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR(ID_ORGANIZADOR)  
);

CREATE TABLE ETAPA (
    ID INT PRIMARY KEY,
    NUMERO_ETAPA INT,
    LONGITUD_KM FLOAT CHECK (LONGITUD_KM <= 100),
    ID_CARRERA INT,
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE CARRERA_CICLISTA (
    ID_CARRERA INT PRIMARY KEY,
    TIPO_TERRENO VARCHAR(100)
);

CREATE TABLE CARRERA_A_PIE (
    ID_CARRERA INT PRIMARY KEY,
    DESNIVEL_TOTAL_METROS FLOAT DEFAULT 0
);

CREATE TABLE BICICLETA_PERMITIDA (
    ID_CARRERA_CICLISTA INT,
    ID_BICICLETA INT,
    PRIMARY KEY (ID_CARRERA_CICLISTA, ID_BICICLETA),
    FOREIGN KEY (ID_CARRERA_CICLISTA) REFERENCES CARRERA_CICLISTA(ID_CARRERA),
    FOREIGN KEY (ID_BICICLETA) REFERENCES BICICLETA(ID)
);


CREATE TABLE PARTICIPANTE_PARTICIPA_CARRERA (
    ID_PARTICIPANTE INT,
    ID_CARRERA INT,
    NUMERO_DORSAL INT,
    PRIMARY KEY (ID_PARTICIPANTE, ID_CARRERA, NUMERO_DORSAL),
    FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTE(ID),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE ORGANIZADOR_ORGANIZA_CARRERA (
    ID_ORGANIZADOR INT,
    ID_CARRERA INT,
    PRIMARY KEY (ID_ORGANIZADOR, ID_CARRERA),
    FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

INSERT INTO PARTICIPANTE (ID, DNI, NOMBRE, EDAD) VALUES
(1, '123456789', 'Juan Perez', 25),
(2, '987654321', 'Maria Rodriguez', 30),
(3, '555555555', 'Carlos Gonzalez', 22);


INSERT INTO DIRECTOR VALUES
(1, 5),
(2, 6),
(3, 7);

SELECT * FROM DIRECTOR;

INSERT INTO CARRERA (ID, FECHA, LUGAR_INICIO, LUGAR_FIN, ID_DIRECTOR)
VALUES (1, '2023-05-15', 'Ciudad A', 'Ciudad B', 1);
