DROP SCHEMA IF EXISTS RESTAURANTE;
CREATE SCHEMA RESTAURANTE;

USE RESTAURANTE;

CREATE TABLE CATEGORÍA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20),
	DESCRIPCIÓN  TINYTEXT
);

CREATE TABLE PLATO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(40),
    DESCRIPCIÓN TINYTEXT,
    FOTO MEDIUMBLOB,
    PRECIO_EN_EUROS DECIMAL(5,2), 
    ID_CATEGORÍA INT, 
    
    FOREIGN KEY (ID_CATEGORÍA) REFERENCES CATEGORÍA(ID)
);

CREATE TABLE INGREDIENTE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(40),
    STOCK FLOAT,
    UNIDAD_MEDIA_STOCK VARCHAR(5)
    );
CREATE TABLE ALÉRGENO_INGREDIENTE (
    ID_INGREDIENTE INT,
    ALÉRGENO VARCHAR(40),
    
    PRIMARY KEY (ID_INGREDIENTE, ALÉRGENO),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE(ID)
    );
    
CREATE TABLE PLATO_USA_INGREDIENTE (
	ID_PLATO INT,
    ID_INGREDIENTE INT,
    CANTIDAD FLOAT,
    UNIDAD_MEDIDA VARCHAR(5),
    
    PRIMARY KEY (ID_PLATO,ID_INGREDIENTE),
    FOREIGN KEY (ID_PLATO) REFERENCES PLATO(ID),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE(ID)
);
