DROP SCHEMA IF EXISTS EMPRESA;

CREATE SCHEMA EMPRESA;

USE EMPRESA;

CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    DIRECCIÓN VARCHAR(50)
); 
CREATE TABLE PRODUCTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL  DEFAULT 'Nuevo producto',
    PRECIO DECIMAL(10 , 2 ) CHECK (PRECIO BETWEEN 1 AND 30000),
    DIVISA VARCHAR(3)
); 
CREATE TABLE EQUIPO (
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(20),
    CATEGORÍA VARCHAR(20) CHECK (CATEGORÍA IN ('Custom', 'Preconfigurado')),
    
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
); 
CREATE TABLE COMPONENTE (
    ID INT PRIMARY KEY, 
    ID_PRODUCTO INT,
    NOMBRE VARCHAR(20),
    TIPO VARCHAR(20)
); 
CREATE TABLE EMPLEADO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    TELÉFONO VARCHAR(9) UNIQUE
); 
CREATE TABLE DIRECTOR (
    ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_ASCENSO DATE,
    BONUS_SALARIO FLOAT,
    DIVISA VARCHAR(3)
); 
CREATE TABLE SECCIÓN (
    ID INT,
    NOMBRE VARCHAR(20),
    ID_DIRECTOR INT
); 
CREATE TABLE CLIENTE_COMPRA_PRODUCTO (
 ID INT AUTO_INCREMENT PRIMARY KEY,
 ID_CLIENTE INT,
 ID_PRODUCTO INT,
FECHA DATE CHECK (FECHA > '2024-01-01'),
 CANTIDAD INT,
 ID_EMPLEADO INT,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID),
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID)

 ); 
CREATE TABLE EQUIPO_COMPUESTO_COMPONENTE (
    ID_EQUIPO INT AUTO_INCREMENT,
    ID_COMPONENTE INT,
    CANTIDAD INT,
    PRIMARY KEY (ID_EQUIPO, ID_COMPONENTE),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_PRODUCTO),
    FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTE(ID)
);
INSERT INTO PRODUCTO (NOMBRE, PRECIO, DIVISA) VALUES
    ('Producto 1', 100.00, 'USD'),
    ('Producto 2', 200.00, 'EUR');

INSERT INTO EQUIPO (NOMBRE, CATEGORÍA, ID_PRODUCTO) VALUES
    ('Equipo 1', 'Custom', 1),
    ('Equipo 2', 'Preconfigurado', 2);
