DROP SCHEMA IF EXISTS PELI;

CREATE SCHEMA PELI;

USE PELI;

CREATE TABLE PELÍCULA  (
ID INT PRIMARY KEY AUTO_INCREMENT,
TÍTULO VARCHAR(50),
AÑO SMALLINT,
NACIONALIDAD VARCHAR(20),
ES_COLOR BOOL,
RESTRICCIÓN_EDAD TINYINT,
RESUMEN TEXT
);
CREATE TABLE PELÍCULA_TIENE_OBSERVACIÓN  (
ID_PELÍCULA INT ,
OBSERVACIÓN VARCHAR(255) ,

PRIMARY KEY(ID_PELÍCULA,OBSERVACIÓN),
FOREIGN KEY(ID_PELÍCULA) REFERENCES PELÍCULA(ID)
);
CREATE TABLE PELÍCULA_TIENE_IDIOMA  (
ID_PELÍCULA INT ,
IDIOMA VARCHAR(50)  ,

PRIMARY KEY(ID_PELÍCULA,IDIOMA),
FOREIGN KEY(ID_PELÍCULA) REFERENCES PELÍCULA(ID)
);
CREATE TABLE DIRECTOR  (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20),
FECHA_NACIMIENTO DATE,
PAÍS_ORIGEN VARCHAR(20)
);
CREATE TABLE ACTOR  (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20),
NACIONALIDAD VARCHAR(20)
);
CREATE TABLE ACTOR_ACTÚA_PELÍCULA  (
ID_ACTOR INT ,
ID_PELÍCULA INT ,
PERSONAJE VARCHAR(20),

PRIMARY KEY(ID_PELÍCULA,ID_ACTOR,PERSONAJE),
FOREIGN KEY(ID_PELÍCULA) REFERENCES PELÍCULA(ID),
FOREIGN KEY(ID_ACTOR) REFERENCES ACTOR(ID)
);
CREATE TABLE DRIRECTOR_DIRIGE_PELÍCULA  (
ID_DIRECTOR INT ,
ID_ACTOR INT,

PRIMARY KEY(ID_DIRECTOR,ID_ACTOR),
FOREIGN KEY(ID_DIRECTOR) REFERENCES DIRECTOR(ID),
FOREIGN KEY(ID_ACTOR) REFERENCES ACTOR(ID)
);